type Query {
  allProducts: [Product]
}

type Product {
  name: String!
  category: String!
  price: Float!
  currency: String!
  image: Image
  bestseller: Boolean
  featured: Boolean
  details: Details
}

type Details @embedded {
  dimensions: Dimensions
  size: Int
  description: String
  recommendations: [Image]
}

type Image @embedded {
  src: String!
  alt: String
}

type Dimensions @embedded {
  width: Int!
  height: Int!
}
